### ISSUE TITLE
Error: couldn’t be opened because there is no such file

### ISSUE THREAD

**Issue by dacarfa** [madeatsampa/MacMagazine-iOS#45]
Fiz o processo igual que esta do GitHub, mas deu esse erro.
error: could not read data from '/Users/Daniel/Desenvolvimento/Swift iOS/MacMagazine-iOS/Pods/Target Support Files/HockeySDK/ResourceBundle-HockeySDKResources-Info.plist': The file “ResourceBundle-HockeySDKResources-Info.plist” couldn’t be opened because there is no such file.

![captura de tela 2016-06-06 as 22 58 27 2](https://cloud.githubusercontent.com/assets/15203691/15843652/3e1780d6-2c3a-11e6-8caa-50e06f95df23.png)

**Comment by brunodelgado** [comment]
Verifique novamente se fez tudo correto. Aqui funcionou sem problemas.

<img width="539" alt="screen shot 2016-06-07 at 12 04 14" src="https://cloud.githubusercontent.com/assets/598889/15863121/284ac5ec-2ca8-11e6-803b-6c0176f42ef9.png">
<img width="487" alt="screen shot 2016-06-07 at 12 05 49" src="https://cloud.githubusercontent.com/assets/598889/15863127/308a9ed0-2ca8-11e6-868a-8578c788571f.png">

**Comment by fsaragoca** [comment]
@dacarfa você está usando o `MacMagazine.xcworkspace`?

**Comment by dacarfa** [comment]
@fsaragoca Cara, fiz o git clone do projeto, depois fiz o '$ sudo gem install cocoapods', depois '$ gem install bundler', depois dentro da pasta do projeto fiz o 'bundle install', depois 'bundle exec pod install'
depois da aquele erro.

**Comment by fsaragoca** [comment]
@dacarfa você está usando o `MacMagazine.xcodeproj` ou o `MacMagazine.xcworkspace` para abrir o projeto no Xcode?

**Comment by dacarfa** [comment]
@fsaragoca MacMagazine.xcworkspace

**Comment by fsaragoca** [comment]
@dacarfa deu algum erro quando rodou `bundle exec pod install`? Qual foi o output?

**Comment by dacarfa** [comment]
@fsaragoca Exclui a pasta, fiz todo o processo novamente, deu certo cara, obrigado.
Qualquer coisa, te chamo de novo.
Abraço.
