### ISSUE TITLE
Cocoapods-keys

### ISSUE THREAD

**Issue by matheusleite** [madeatsampa/MacMagazine-iOS#46]
Quando dou um `pod install` ele pede as keys, dou um `enter` mas não avança na instalação.

Usando Mac OSX El Capitan.

**Comment by fsaragoca** [comment]
@matheusleite acho que o nosso README está incorreto, precisa inserir pelo menos uma letra pra conseguir avançar. Pode tentar novamente? Coloque `a` como key.

**Comment by rgalba** [comment]
@matheusleite confere tua versão do ruby. Pra instalar tudo do cocoapods, tem que ser ruby 2.2.3+. Mandei uma PR pra isso. Além disso, coloca o log aqui pra gente analisar.

**Comment by brunov0id** [comment]
Ocorreu o seguinte erro para mim, após instalar _cocoapods-keys_ e dar _pod install_

```
---------------------------------------------
Error loading the plugin `cocoapods-keys-1.7.0`.
LoadError - cannot load such file -- /Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.7.0/lib/cocoapods_plugin.rb
---------------------------------------------
```

para solucionar este problema, utilizei o seguinte comando:

`sudo chmod -R go+r /Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.7.0`

em seguida, tentei novamente o _pod install_ e pronto :)
quando solicitou a chave, apenas digite **a** e a instalação deu continuidade.

**Comment by cesarbars** [comment]
Encerrando aqui, parece que as issues reportadas foram resolvidas.

Vou rastrear o reportado pelo @fsaragoca sobre a chave precisar ter ao menos 1 caractere
