### ISSUE TITLE
Corrigir texto explicativo sobre pushes

### ISSUE THREAD

**Issue by rfischmann** [madeatsampa/MacMagazine-iOS#53]
Ao abrir a área de ajustes do app, há um parágrafo de texto no fim.

Alterar "Pushes para todos os posts" para "Push para todos os posts", tal como é de fato a opção acima do parágrafo.

Se possível, remover também o espaçamento vazio que há entre "Ajustes do MacMagazine" e as opções em si (começando por "Licenças").

**Comment by brunodelgado** [comment]
O espaçamento entre o texto e o texto e as opções é padrão se você não passar nenhum título para o grupo, como descreve a documentação da Apple
https://developer.apple.com/library/ios/documentation/PreferenceSettings/Conceptual/SettingsApplicationSchemaReference/Articles/PSGroupSpecifier.html#//apple_ref/doc/uid/TP40007009-SW1

![screen shot 2016-06-22 at 3 19 05 pm](https://cloud.githubusercontent.com/assets/598889/16278459/70bc5b06-388d-11e6-85d5-1bd39d0a025d.png)

Porém, mesmo colocando um texto (só como teste) o espaçamento não está sumindo.
E ai Apple?! 😅 

![simulator screen shot jun 22 2016 2 37 22 pm](https://cloud.githubusercontent.com/assets/598889/16278572/d53782c2-388d-11e6-8cd7-697ec55c4331.png)


De qualquer forma o o texto foi corrigido na PR #65

**Comment by brunodelgado** [comment]
Parece que o aplicativo Fabric também "sofre" desse espaçamento.

![img_0002](https://cloud.githubusercontent.com/assets/598889/16278926/1ef169ae-388f-11e6-80f8-74520459e3ec.PNG)
