### ISSUE TITLE
Crash ao tentar abrir alguns links

### ISSUE THREAD

**Issue by leoformaggio** [madeatsampa/MacMagazine-iOS#61]
Com certa frequência este crash ocorre ao tentar abrir links de apps, como nos posts de _Ofertas do dia na App Store_.

[MacMagazine  6-21-16, 7-14 PM.crash.zip](https://github.com/madeatsampa/MacMagazine-iOS/files/326697/MacMagazine.6-21-16.7-14.PM.crash.zip)

**Comment by cesarbars** [comment]
@leoformaggio qual exatamente era o problema aqui?

**Comment by leoformaggio** [comment]
@cesarbars o `targetURL` era `nil`

**Comment by leoformaggio** [comment]
@cesarbars na verdade o crash não acontece apenas com links da App Store. Editei o título da issue e do PR pra ficar mais genérico

**Comment by cesarbars** [comment]
@leoformaggio vou passar a discussão pro PR pra ficar mais pertinente ao código

**Comment by rfischmann** [comment]
Não sei se algo nos últimos dias fez esse bug se manifestar mais, porém só de ontem para hoje recebemos 4-5 reclamações de leitores. Talvez devamos providenciar logo a liberação de um update?

**Comment by leoformaggio** [comment]
@rfischmann você sabe dizer se houve alguma alteração na forma como são geradas as páginas? O problema está relacionado à links com `target="_blank"` no HTML. Se não mudou nada, talvez o aumento nas reclamações esteja apenas acompanhando o crescimento de uso do app.

**Comment by rfischmann** [comment]
Nossa, @leoformaggio, agora que você perguntou isso que eu liguei uma coisa à outra. De fato, há alguns dias atualizamos um plugin do WordPress responsável por gerenciar os links externos em posts, adicionar o `target="_blank"` e aquele iconezinho ao lado que identifica que a pessoa sairá do MacMagazine.

Eu só não imaginei que isso poderia causar algum problema no app, até porque a estrutura do link não tem nada de mirabolante. Veja um exemplo de hoje:

`<p>Se corrida é uma das atividades físicas que você pratica (ou está planejando praticar), o aplicativo <a href="https://www.facebook.com/AppRunShot/" data-wpel-link="external" target="_blank" rel="external noopener noreferrer" class="ext-link wpel-icon-right"><strong>RunShot</strong><span class="wpel-icon wpel-image wpel-icon-6"></span></a> pode ser um ótimo aliado.</p>`

De qualquer forma, como os relatos aumentaram muito de uns dias para cá, é bem provável que tenha sido a causa mesmo.

**Comment by leoformaggio** [comment]
@rfischmann deve ter sido isso mesmo, então. Eu mandei um PR pra evitar o crash, aguardando o review. Obrigado pelo retorno 😉
