### ISSUE TITLE
Contador de notificações, "badge" não é zerado

### ISSUE THREAD

**Issue by leonardo-ferreira07** [madeatsampa/MacMagazine-iOS#68]
- O contador das notificações push _badge_ é zerado quando o app é aberto, porém após isto, quando o app recebe uma nova notificação, esse contador não conta uma notificação no _badge_, mas sim um acúmulo de todas que já foram recebidas, por exemplo, no meu caso já contam 155.
- Sou desenvolvedor iOS também, e acredito que esse problema está em quem faz o envio das notificações, que eu acredito não ser o app (não olhei os fontes) neste projeto. Deve ter algum problema no momento em que esse contador das notificações deveria ser zerado, antes de associar isto a uma _push notification_ e enviar a mesma.

Espero ter ajudado 👍

**Comment by fsaragoca** [comment]
Obrigado pela ajuda @leonardo-ferreira07, o problema na verdade era a `api_key` da API de notificações estava errada, então o aplicativo não conseguia atualizar o valor da badge no servidor. Tudo resolvido agora!
